services:
  src:
    build: .
    ports:
      - "8000:80"
    env_file:
      - .env  
    depends_on:
      - db 
    command: >
      sh -c "alembic upgrade head &&
             uvicorn src.main:app --host 0.0.0.0 --port 80"
  db:  
    image: postgres:15  
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data  

volumes:
  postgres_data: